export const GameTag = {
  ACTION: "action",
  ADVENTURE: "adventure",
  RPG: "rpg",
  STRATEGY: "strategy",
  SIMULATION: "simulation",
  SPORTS: "sports",
  RACING: "racing",
  PUZZLE: "puzzle",
  PLATFORMER: "platformer",
  SHOOTER: "shooter",
  FIGHTING: "fighting",
  HORROR: "horror",
  SURVIVAL: "survival",

  OPEN_WORLD: "open_world",
  METROIDVANIA: "metroidvania",
  ROGUELIKE: "roguelike",
  ROGUELITE: "roguelite",
  SOULSLIKE: "soulslike",
  TACTICAL: "tactical",
  TURN_BASED: "turn_based",
  REAL_TIME: "real_time",
  SANDBOX: "sandbox",
  STEALTH: "stealth",
  DUNGEON_CRAWLER: "dungeon_crawler",
  PARTY_BASED_RPG: "party_based_rpg",
  JRPG: "jrpg",
  ARPG: "action_rpg",
  RTS: "rts",
  TOWER_DEFENSE: "tower_defense",
  CITY_BUILDER: "city_builder",
  GRAND_STRATEGY: "grand_strategy",
  AUTO_BATTLER: "auto_battler",
  CARD_GAME: "card_game",
  DECKBUILDING: "deckbuilding",

  SINGLEPLAYER: "singleplayer",
  MULTIPLAYER: "multiplayer",
  COOP: "coop",
  ONLINE: "online",
  LOCAL_MULTIPLAYER: "local_multiplayer",
  SPLIT_SCREEN: "split_screen",
  MMO: "mmo",
  BATTLE_ROYALE: "battle_royale",
  PVP: "pvp",
  PVE: "pve",
  ASYMMETRIC_MULTIPLAYER: "asymmetric_multiplayer",

  FIRST_PERSON: "first_person",
  THIRD_PERSON: "third_person",
  TOP_DOWN: "top_down",
  ISOMETRIC: "isometric",
  SIDE_SCROLLING: "side_scrolling",

  STORY_RICH: "story_rich",
  CASUAL: "casual",
  HARDCORE: "hardcore",
  ATMOSPHERIC: "atmospheric",
  EXPLORATION: "exploration",
  PUZZLE_SOLVING: "puzzle_solving",
  FAST_PACED: "fast_paced",
  DIFFICULT: "difficult",
  PERMADEATH: "permadeath",
  PROCEDURAL_GENERATION: "procedural_generation",
  RESOURCE_MANAGEMENT: "resource_management",
  BASE_BUILDING: "base_building",
  CRAFTING: "crafting",
  LOOT: "loot",
  GRINDING: "grinding",

  FANTASY: "fantasy",
  DARK_FANTASY: "dark_fantasy",
  SCI_FI: "sci_fi",
  CYBERPUNK: "cyberpunk",
  POST_APOCALYPTIC: "post_apocalyptic",
  ZOMBIES: "zombies",
  MEDIEVAL: "medieval",
  HISTORICAL: "historical",
  WAR: "war",
  MILITARY: "military",
  SPACE: "space",

  PIXEL_ART: "pixel_art",
  RETRO: "retro",
  HAND_DRAWN: "hand_drawn",
  LOW_POLY: "low_poly",
  ANIME: "anime",
  CARTOON: "cartoon",
  REALISTIC: "realistic",

  INDIE: "indie",
  SHORT: "short",
  RELAXING: "relaxing",
  EDUCATIONAL: "educational",
  FAMILY_FRIENDLY: "family_friendly"
} as const;

export type GameTag = typeof GameTag[keyof typeof GameTag];